# Configuration file

general {
    # Global ID Biome for Planets/Moons
    I:IDSpaceBiome=138

    # Global ID Biome for Planets/Moons (Shallow Waters Biome)
    I:IDSpaceShallowWatersBiome=137

    # Global ID Biome for Planets/Moons (Oceans Biome)
    I:IDSpaceOceansBiome=136

    # Global ID Biome for Planets/Moons (Deep Oceans Biome)
    I:IDSpaceDeepOceansBiome=135

    # Global ID Biome for Planets/Moons (Low Plains Biome)
    I:IDSpaceLowPlainsBiome=134

    # Global ID Biome for Planets/Moons (Mid Plains Biome)
    I:IDSpaceMidPlainsBiome=133

    # Global ID Biome for Planets/Moons (Low Hills Biome)
    I:IDSpaceLowHillsBiome=132

    # Global ID Biome for Planets/Moons (High Plateaus Biome)
    I:IDSpaceHighPlateausBiome=131

    # Global ID Biome for Planets/Moons (Mid Hills Biome)
    I:IDSpaceMidHillsBiome=130

    # Global ID Biome for Planets/Moons (Rocky Waters Biome)
    I:IDSpaceRockyWatersBiome=129

    # Global ID Biome for Planets/Moons (Low Islands Biome)
    I:IDSpaceLowIslandsBiome=128

    # Global ID Biome for Planets/Moons (Partially Submerged Biome)
    I:IDSpacePartiallySubmergedBiome=127

    # Global ID Biome for Planets/Moons (Beach Biome)
    I:IDSpaceBeachBiome=126

    # Biome ID for World Engine
    I:IDWorldEngineBiome=125
}


