; {"viewmode":"DEFAULT","active":true}
{"item":{"strId":"minecraft:coal","Count":1,"Damage":"0S"},"factor":-1,"ingredient":false}
{"item":{"strId":"minecraft:stick","Count":1,"Damage":"0S"},"factor":-1,"ingredient":false}
