; {"groups":{"0":{"viewmode":"DEFAULT","crafting":false,"collapsed":false}}}
{"item":{"Count":1,"Damage":"0S","strId":"minecraft:coal"},"factor":1,"ingredient":false}
{"item":{"Count":1,"Damage":"0S","strId":"minecraft:stick"},"factor":1,"ingredient":false}
{"item":{"Count":0,"Damage":"0S","strId":"minecraft:glass"},"factor":1,"ingredient":false}
; {"groups":{"0":{"viewmode":"DEFAULT","crafting":false,"collapsed":false}}}
